### ISSUE TITLE
Having trouble to return ajax data

### ISSUE THREAD

**Issue by MaikoORP** [n1crack/Datatables#1]
Can't generate the json.
ajax code:

    $config = [ 'host'     => 'localhost',
    'port'     => '3306',
     'username' => 'root',
    'password' => '',
    'database' => 'sys_db_gestao' ];
    $dt = new Datatables( new MySQL($config) );
    $dt->query("SELECT t.id as tokenId, t.tokenCode as tokenCode, cli.name as clientName,
    cit.name as cityName,
     cast(DATE_FORMAT(t.dateOpen,'%d/%m/%Y %H:%i:%s') as char(20)) as dateOpen,
    t.status as tokenstatus
    FROM token t
    LEFT JOIN client cli on cli.id = t.idClient
    LEFT JOIN city cit on cit.id = t.idCity
    ");
    echo $dt->generate();

and the browser console gives me this:
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: 4096</p>
<p>Message:  Argument 1 passed to PHPSQLParser\builders\WhereBuilder::build() must be of the type array, boolean given, called in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\gestao\vendor\greenlion\php-sql-parser\src\PHPSQLParser\builders\SelectStatementBuilder.php on line 74 and defined</p>
<p>Filename: builders/WhereBuilder.php</p>
<p>Line Number: 112</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Invalid argument supplied for foreach()</p>
<p>Filename: builders/WhereBuilder.php</p>
<p>Line Number: 114</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: 4096</p>
<p>Message:  Argument 1 passed to PHPSQLParser\builders\WhereBuilder::build() must be of the type array, boolean given, called in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\gestao\vendor\greenlion\php-sql-parser\src\PHPSQLParser\builders\SelectStatementBuilder.php on line 74 and defined</p>
<p>Filename: builders/WhereBuilder.php</p>
<p>Line Number: 112</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Invalid argument supplied for foreach()</p>
<p>Filename: builders/WhereBuilder.php</p>
<p>Line Number: 114</p>

</div><br />
<b>Fatal error</b>:  Call to a member function fetch_assoc() on a non-object in <b>C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\gestao\vendor\ozdemir\datatables\src\DB\MySQL.php</b> on line <b>40</b><br />

Help me?

**Comment by n1crack** [comment]
I have made some changes in the library. Parser removed.
