### ISSUE TITLE
Mysql table with dashes in name causes error

### ISSUE THREAD

**Issue by 13ran** [n1crack/datatables#102]
Tables with dashed column names causes an error

This works:
```
$dt->query("SELECT
    `test-test` AS `test`
FROM
    `test`");
```

This causes an error:
```
$dt->query("SELECT
    `test-test`
FROM
    `test`");
```

**Comment by n1crack** [comment]
I'm checking.

**Comment by n1crack** [comment]
I think I made it on purpose since it is not recommended to use dash in the columns. Using dashes (-) in column names is generally discouraged because many programming languages, databases, and tools interpret the dash as a subtraction operator or other special character.

you can use underscore instead.

**Comment by 13ran** [comment]
If the column name has `` around it, it shouldn't cause any problems. I'd really like to avoid renaming all the columns in my database as it already has millions of rows

**Comment by n1crack** [comment]
what about using like this: 

```php
$dt->query("SELECT
    `test-test` AS `test_test`
FROM
    `test`");
```

In this case, you dont have to rename your queries.

**Comment by 13ran** [comment]
Causes issues with filtering as `test_test` doesnt exist in the database

**Comment by n1crack** [comment]
Not sure whats wrong.. Its working for me as expected.

![image](https://github.com/n1crack/datatables/assets/712404/64283b0b-2950-41ae-959a-2aed92355320)

**Comment by n1crack** [comment]
![image](https://github.com/n1crack/datatables/assets/712404/4bb46fc9-29d0-4d3e-aa11-d22761d612e8)

and this is the default filtering

**Comment by n1crack** [comment]
Can you show me the error you get ? maybe there is another problem ?

**Comment by 13ran** [comment]
Sorry you are correct it does work. My request was just timing out because it was doing a LIKE search. 

How do I make it do an exact search? This is the data being sent to the server

```
columns[9][data]: phone_number
columns[9][name]: 
columns[9][searchable]: true
columns[9][orderable]: true
columns[9][search][value]: ^123456$
columns[9][search][regex]: true
```
Also is there a way to filter on multiple columns with OR? Say for example the column being searched is 'phone_number' I would like the query to be where 'phone_number' = value or 'some_other_column' = value

**Comment by n1crack** [comment]
When you type in search input, all columns that has `searchable: true`  are being search with "LIKE" and merged with 'OR'. 

Lets say, you need to filter by full text, then you can bypass default filter like : 

```php
    $dt->filter('test_test', function () {
        return $this->column->name.' = '. $this->escape($this->searchValue());
    });
```

**Comment by 13ran** [comment]
Thanks. Now how would I make that filter apply only when searchValue() has a value?

**Comment by n1crack** [comment]
Ah sorry, here it is:

```php
   $dt->filter('test_test', function () {
        if ($this->searchValue() === '') {
            return;
        }
        return $this->column->name.' = '. $this->escape($this->searchValue());
    });

```

**Comment by 13ran** [comment]
I just looked at the getQuery() log and that still causes the search term to be added to the query

**Comment by n1crack** [comment]
Yea you are right, can you try this one ?

```php
   $dt->filter('test_test', function () {
        if ($this->searchValue() === '') {
            return '';
        }
        return $this->column->name.' = '. $this->escape($this->searchValue());
    });
```

**Comment by 13ran** [comment]
That works. Thanks again for all the help!!
