### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by 13ran** [n1crack/datatables#103]
When I have multiple filters and one is empty it still adds AND to the query and causes a pdo error. If all filters have values  or if only one filter is defined the query works.

```
  $dt->filter('phone_number', function () {
    if ($this->searchValue() === '') {
      return '';
    }
    return '('.$this->column->name.' = '.$this->escape($this->searchValue()).' OR phone_number_formatted = '.$this->escape($this->searchValue()).')';
  });

  $dt->filter('year', function () {
    if ($this->searchValue() === '') {
      return '';
    }

    $val = explode('-delim-', $this->searchValue());

    return $this->between($val[0], $val[1] ?? null);
  });
```

`Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND )t'`

**Comment by n1crack** [comment]
fixed adding 'AND' for empty values are fixed.

but since filter was originally added for the individual column filtering, I think we need to add a new method or some parameters to make it available for global too. Let me think about it for a while.

**Comment by 13ran** [comment]
Sounds good thanks. It would be awesome if there was an exact match function so I don't have to define my own function

**Comment by 13ran** [comment]
```
if ($this->searchValue() === '') {
      return '';
    }
```

No longer works after the last update. When using multiple filters if at least one has a value all end up in the query

**Comment by n1crack** [comment]
- added  `forceExactMatch` method to use '=' instead of 'LIKE' as default filtering behavior.

```php
$dt->forceExactMatch(true);
```

- added 3rd optional parameter to filter method. (it is INDIVIDUAL by default, as it is before..)

`\Ozdemir\Datatables\CustomFilterType::INDIVIDUAL` : uses this filter only when individual search happens
`\Ozdemir\Datatables\CustomFilterType::GLOBALLY` : uses this filter only when global search happens
`\Ozdemir\Datatables\CustomFilterType::ALL`  : uses this filter on both situations

```php
    $dt->filter('test_test', function () {
        if ($this->searchValue() === '') {
            return '';
        }
        return $this->column->name.' = '. $this->escape($this->searchValue());
    }, \Ozdemir\Datatables\CustomFilterType::GLOBALLY);

```
