### ISSUE TITLE
How to unset a field?

### ISSUE THREAD

**Issue by mnajafzadeh** [n1crack/datatables#13]
Hi,

Thank you for your excellent job.

I want to unset a field that I have selected in my query statement. For example:

$dt->query("SELECT id, name, phone");

I only want to get name and phone in my table but, I also need id field to use it in my edit function but I do not need id in my table output.

$dt->edit('name', function($data) {
    return callback_view($data['id'], $data['name']);
});

Thank you.

**Comment by n1crack** [comment]
I can add a "hide()" method that removes columns from output in upcoming patches.

if you need only id column, I think you can set visible attribute to false to that column with javascript.

**Comment by mnajafzadeh** [comment]
Hi,

I didn't want to disable id column, it was just an example.
BTW, I used the **"visible": false** trick from Datatables in my jQuery code but, you had a method in your legacy library that was **$dt->unset_column('error_message')** and it was very useful and it is removed in your new library.

Thank you so much.

**Comment by n1crack** [comment]
Updated the library.

it should work.. can you test it ?

**Comment by mnajafzadeh** [comment]
Thank you so much for the update.

**Comment by moudarir** [comment]
Thank you for the update. it's very usefull.

**Comment by mnajafzadeh** [comment]
I have tested and it is working as well.
Thank you.
