### ISSUE TITLE
how to use same reference field name in two different column?

### ISSUE THREAD

**Issue by atukilham** [n1crack/datatables#14]
Thanks for your library, it's helped me so much..
I want to ask about use same field name in edit method for different column.
cz i want to make two column contain checkboxes, (eg: column A contain checkbox A, column B contain checkbox B), and use same field for value.
For 1 column in the table, it's possible to use `$dt->edit(field_name, function)`, but how about two different column with same reference field name?
Can we use it?
Thanks.. (sorry for my bad english)

**Comment by n1crack** [comment]
Yes, it is possible. 
Let's say you have three columns (id, title, body)

$dt->edit('id', function($data){
// you can access all columns data with $data
    return $data['id'] . ' and ' $data['title'] ;
});

**Comment by atukilham** [comment]
Thanks so much, @n1crack 
It's work now..
:+1:
