### ISSUE TITLE
how to modify request data

### ISSUE THREAD

**Issue by anchetaWern** [n1crack/datatables#15]
I'm using this library for SQLite. And I had a problem with pivot tables that's why I just hard-coded what would usually be written in query.

```php
foreach($data as $row){ 
       $flat_data[$row['some_id']] = [ ... ]
}
```

Now as you might expect, the problem now would be the limit. Because the limit is only applied to the query, it will no longer be the same as the number of records actually being returned. It would probably mess up the pagination as well. So I was thinking of modifying the request data coming from datatables on the client side. Tried the suggestion [here](https://stackoverflow.com/questions/36812476/how-to-change-value-of-a-request-parameter-in-laravel) but it doesn't really work. It still honors the limit selected on the client side.

```php
public function getData(Request $request)
{
  $request->merge(['length' => 1000]);
} 
```

Any ideas?

**Comment by n1crack** [comment]
What was the problem with pivot tables?

**Comment by anchetaWern** [comment]
@n1crack SQLite doesn't support it.

**Comment by n1crack** [comment]
Can you show me your query ? your tables or something ? maybe we can find another way ?

**Comment by anchetaWern** [comment]
@n1crack I tried to get help on Stackoverflow before: https://stackoverflow.com/questions/45096679/sql-how-to-flatten-result-from-grouping

Here's the fiddle: https://www.db-fiddle.com/f/jShqr92EEQTgVBaA3pjAfo/3
