### ISSUE TITLE
any idea get data from store procedure?

### ISSUE THREAD

**Issue by atukilham** [n1crack/datatables#16]
i created a store procedure, and i want call it.
but i think it's not possible use `$datatables->query("CALL store_procedure()")` ,
cz query's function will create new statement select like `select * from (CALL store_procedure())` and i thinks it doesn't work.
I try to find how to execute store procedure, but until now i have no idea.

Can you help me?
Thanks

**Comment by n1crack** [comment]
Sorry, it is not possible..
But you can try functions instead procedures. 

see https://stackoverflow.com/a/14507763/6333300 . I haven't tried it yet but I think it should work.

**Comment by atukilham** [comment]
okay, I'll try..
thanks a lot @n1crack .
.
