### ISSUE TITLE
Parameter must be an array or an object that implements Countable in

### ISSUE THREAD

**Issue by caturseptian** [n1crack/datatables#26]
Apache Server,
PHP v7.2.0,
MySQL v5.7.19,

PHP Native

<br />
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>***:\***\***\***\vendor\ozdemir\datatables\src\Datatables.php</b> on line <b>234</b><br />
<br />
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>***:\***\***\***\vendor\ozdemir\datatables\src\Datatables.php</b> on line <b>243</b><br />
<br />

**Comment by n1crack** [comment]
I’ll look into it today. Thanks for sharing this.

**Comment by n1crack** [comment]
It should be fixed on https://github.com/n1crack/datatables/commit/725df9e9bdad2f75e4259835840453825d4307d2

**Comment by caturseptian** [comment]
thanks Yusuf
