### ISSUE TITLE
Slow page load times with large database, 300,000+ rows

### ISSUE THREAD

**Issue by tombs007** [n1crack/datatables#27]
Let me start of by saying thanks for sharing this project.

Please forgive me as I am new to working with PHP/Sqlite.

I am getting slow page load times when using the sqlite implementation out of the box.
Load times average 2+ seconds.

Using a similar setup with server side and mysql as provided by datatables I get 150ms load times.

Could you provide suggestions on how to speed up load times?

**Comment by TiTnOuK** [comment]
I hope it can help you : https://stackoverflow.com/a/811862

**Comment by tombs007** [comment]
Thanks for the link @TiTnOuK I will review that in greater detail.

I should have mentioned that my db is currently 101MB in size, with a single table and 6 columns.

**Comment by n1crack** [comment]
Hey, 

I didn't try 300k data with sqlite. I also don't know if it is something with my library but I can recommend you to read this link : https://medium.com/@JasonWyatt/squeezing-performance-from-sqlite-indexes-indexes-c4e175f3c346 

I'll look into it when I have free time.
