### ISSUE TITLE
Conditional where clauses?

### ISSUE THREAD

**Issue by bikedorkjon** [n1crack/datatables#29]
I'm in the process of upgrading from your 0.9 standalone version that used Active Record. Something that has changed is I've noticed that it appears you can no longer do something like this:

`if(isset($_GET['type'])) {
	$type = explode(',', $_GET['type']);
	for ($j=0; $j < count($type); $j++) {
        $datatables->where('ubbt_TR_TYPES.TYPE_ID !=', $type[$j]);
	}
}`

Is this still possible and if not do you have recommendations on how to accomplish the above?

**Comment by n1crack** [comment]
Yes things changed :)

 
Hm.. you can do something like this in your sql query: 

```php
$type_id = $_GET['type']; // you should escape it against sql injection.
$datatables->query('SELECT id, name, type_id FROM myTable WHERE type_id != ' .  $type_id );

$datatables->generate();
```

i will try to add where method to implement that functionality as default when I have free time.

**Comment by bikedorkjon** [comment]
I'm really glad to see that this project is still going, kudos to you!

In the meantime is there any security reason why I couldn't use the 0.9 version of this that uses the $dt->where? Something you will see in my conditional there is that it's looping through all the type_ids provided there. Granted probably would be easier to us IN and pass in a comma separated list of ids.

Thanks!

**Comment by blueston22** [comment]
Love this project! For the life of me I cannot figure out how to search case insensitive. It will only search case sensitive. Many thanks in advnace

**Comment by n1crack** [comment]
2.0 will support conditional filters.

````php
// your code

if (1===1) { // some conditions or loops can be used here
  $datatables->filter('id', function ($escape, $search){
      $val1 = $escape(6); 
      $val2 = $escape(170);
      return "id BETWEEN $val1 AND $val2";
  });
}
$datatables->generate();
````

**Comment by PollyCatZ** [comment]
Hello friend, what if aliases and PhalconAdapter are used?
`
$builder = $this->modelsManager->createBuilder()
    ->from(['o' => Orders::class])
    ->columns([
        'o.id as id', 
        'o.sticker as sticker',
        'o.status as status',

        'item.id as item_id',
        'item.name as item_name',

        'c.id as client_id',
        'c.phone as client_phone',

        'section.title as section_title',
        'cat.title as cat_title',
        'brand.title as brand_title',
    ])
    ->leftJoin(Items::class, 'item.barcode = o.barcode', 'item')
    ->leftJoin(Sections::class, 'section.id = item.section_id', 'section')
    ->leftJoin(Cats::class, 'cat.id = item.cat_id', 'cat')
    ->leftJoin(Brands::class, 'brand.id = item.brand_id', 'brand')
    ->leftJoin(Clients::class, 'c.id = o.client_id', 'c')
    ->getQuery()
    ->getSql();

$dt = new Datatables(new PhalconAdapter($this->di, 'db'));
$dt->query($builder['sql']);

$dt->filter('status', function ($status) {
    $this->log(123); //this piece of code is not executed at all <<<<<<<<<<<<<<<<<<<<<<<<<<<
    return 'o.status = 1';
});

echo $dt->generate()->toJson();
`
