### ISSUE TITLE
Library not working on PHP5.3 due to [], PHP5.3 only support array().

### ISSUE THREAD

**Issue by irvine48** [n1crack/datatables#30]
Facing this issue on PHP 5.3.8.

**Comment by n1crack** [comment]
Thank you for reporting this. 
I’ll update it when I get home. 

or I can merge a pr if you can create one.

**Comment by irvine48** [comment]
Sorry to tell you i might not skillful enough to make a pull request,
I done some modification on the source code from this library, it look working at the moment. After your update i will update again and any issues will update to you.

Thanks for your coding !
