### ISSUE TITLE
Datatables table configuration not working - sort, number of rows, paging, etc..

### ISSUE THREAD

**Issue by irvine48** [n1crack/datatables#31]
Server side not processing this $_GET information sending from ajax?

>   ["iColumns"]=>
>   string(2) "11"
>   ["sColumns"]=>
>   string(10) ",,,,,,,,,,"
>   ["iDisplayStart"]=>
>   string(1) "0"
>   ["iDisplayLength"]=>
>   string(2) "10"
>   ["sSearch_0"]=>
>   string(0) ""
>   ["bRegex_0"]=>
>   string(5) "false"
>   ["bSearchable_0"]=>
> .....

}

**Comment by irvine48** [comment]
by turning off this two make it processing by datatables without server side support, which way is better? server side produce require data or give a large chunk of data and let datatables process it?

> $('#table_merchant_list').DataTable( {
> // "bProcessing": true,
> // "bServerSide": true,
> ...
> });

**Comment by n1crack** [comment]
Can you show me your setup? Which version of datatables do you use?  
Sorting and pagination etc. must work as expected.

**Comment by TiTnOuK** [comment]
@irvine48 Server side is better when you have to display a lot of results from an expensive query (mysql or another). You will be able to recover only the elements to be displayed according to the pagination parameters (**start** and **length**) sent during the server request.
On the other hand if you have little data to display, the client side does the job very well.

For your problem, I think you use incompatible datatables lib version (< 1.10). Try to use last stable version from offical website [https://datatables.net/download/](https://datatables.net/download/)

**Comment by irvine48** [comment]
Hi, here attached with my setup for ajax without server side processing for configuration.

> 
> <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
> <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/3.2.4/css/fixedColumns.dataTables.min.css">
> <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
> <script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.2.4/js/dataTables.fixedColumns.min.js"></script>


> 	$(document).ready(function() {
> 		$('#table_merchant_list').DataTable( {
> 			"order": [[ 0, "asc" ]],
> 			"pageLength": 5,
> 			"scrollX": true,
> 			"fixedColumns": {
> 				leftColumns: 2
> 			},
> 			// "bProcessing": true,
> 			// "bServerSide": true,
> 			"sAjaxSource": "test/jxindex",
> 			"columns": [
> 	                        { data: "id" },
> 				{ data: "name" },
> 				{ data: "city" },
> 				{ data: "tel" },
> 				{ data: "email" },
> 				{ data: "contact" },
> 				{ data: "created_date" },
> 				{ data: "status" },
> 				{ sortable: false, "render": function ( data, type, full, meta ) {
> 				var rowID = full["id"];
> 				return '<a href=/contacts/'+encodeURI(rowID)+' class="btn btn-info">Edit</a>';
> 				}
> 				}
> 			]
> 		} );
> 	} );

	function jxIndex($request, $response)
	{		
		$config = array(
				'host'     => 'localhost',
				'port'     => '3306',
				'username' => 'xxx',
				'password' => 'xxx',
				'database' => 'xxx' );

		$dt = new Datatables( new MySQL($config) );

		$dt->query("
		Select 
			id, name, city, tel, email, contact, created_date, status
		FROM 
			contact
		");

		echo $dt->generate();
		exit();
	}

what i see here is, retrieve whole chunk of data instead of process the parameters from ajax to retrieve require data. So maybe can include in next update.

**Comment by n1crack** [comment]
"bServerSide": true,    

you should enable this. Otherwise whole data will be loaded. 

your setup looks ok to me.
