### ISSUE TITLE
Support search type SQL ( between and IN )

### ISSUE THREAD

**Issue by luqmanpaisal** [n1crack/datatables#32]
Possible that search individual column for between 
example
date range
& for IN 
Multiple tags search

and also can support pattern search method like https://github.com/vedmack/yadcf

**Comment by n1crack** [comment]
added escape function as param. so you can use it.

if you want to use it with yadcf, this is an example:

````php
  $datatables->filter('id', function ($escape, $search){
      //   $search = '3-yadcf_delim-150';
      list($val1, $val2) = explode("-yadcf_delim-", $search);
      $val1 = $escape($val1);
      $val2 = $escape($val2);
      return "id BETWEEN $val1 AND $val2";
  });
````

**Comment by n1crack** [comment]
2.0 released. Please let me know if there is any further inconvenience.

**Comment by n1crack** [comment]
yadcf support.

https://datatables.ozdemir.be/custom-filter2
