### ISSUE TITLE
undefined offset error

### ISSUE THREAD

**Issue by kasperfish** [n1crack/datatables#34]
got this error with a simple select * from table

Notice: Undefined offset: 2 in /var/www/html/explorer/vendor/ozdemir/datatables/src/Datatables.php on line 220

Notice: Undefined index: ASC in /var/www/html/explorer/vendor/ozdemir/datatables/src/Datatables.php on line 220

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 10 OFFSET 0' at line 1 in /var/www/html/explorer/vendor/ozdemir/datatables/src/DB/MySQL.php:38 Stack trace: #0 /var/www/html/explorer/vendor/ozdemir/datatables/src/DB/MySQL.php(38): PDOStatement->execute(Array) #1 /var/www/html/explorer/vendor/ozdemir/datatables/src/Datatables.php(73): Ozdemir\Datatables\DB\MySQL->query('Select * from (...') #2 /var/www/html/explorer/vendor/ozdemir/datatables/src/Datatables.php(228): Ozdemir\Datatables\Datatables->execute() #3 /var/www/html/explorer/explorer_api2.php(55): Ozdemir\Datatables\Datatables->generate() #4 {main} thrown in /var/www/html/explorer/vendor/ozdemir/datatables/src/DB/MySQL.php on line 38

**Comment by n1crack** [comment]
You should define your columns for some reasons
