### ISSUE TITLE
Search Case Insensitive

### ISSUE THREAD

**Issue by blueston22** [n1crack/datatables#36]
Love this project! For the life of me I cannot figure out how to search case insensitive. It will only search case sensitive. Many thanks in advance.

**Comment by blueston22** [comment]
I have found the solution.

I removed the iteration for "each" word search. See below

$searchinput = (string)$this->input('search')['value'];
        $length = strlen($searchinput);
        $allcolumns = $this->input('columns');

        if ($searchinput == '' || $length < 2)
        {
            return null;
        }

        $search = [];
        $searchinput = preg_replace("/[^\wá-žÁ-Ž]+/", " ", $searchinput);
        $new_search = strtoupper($searchinput);

        $lookfor = [];
        foreach ($this->columns as $key => $column) {

            if(array_key_exists($key,$allcolumns)){

                if ($allcolumns[ $key ]['searchable'] == 'true') {
                    $lookfor[] = "UPPER(".$column . ") LIKE  '%". $new_search . "%'  ";
                }
            }
        }
        $search[] = "(" . implode(" OR ", $lookfor) . ")";

I know I need to escape...But this gives the general direction.

**Comment by blueston22** [comment]
And I am using a DB2, ibmi

**Comment by n1crack** [comment]
As I thought, it is something related to DB. There is an article [in this post about db2](https://www.ibm.com/developerworks/data/library/techarticle/0203adamache/0203adamache.html) which is you may have already be read.

it says: 
> The short answer is that DB2 for Linux®, UNIX®, and Windows® Version 7.2 is case sensitive: BLAIR is not the same as Blair.

**Comment by blueston22** [comment]
Yep. Thanks for the follow up...great package. Love it.
