### ISSUE TITLE
Count request retrieving whole data set

### ISSUE THREAD

**Issue by vedmant** [n1crack/datatables#39]
Your code for count is making request and retrieving data for whole table, that will crash on larger tables when it will try to retrieve more than 100k records, you have identical query and count methods:

    public function query($query)
    {
        $sql = $this->pdo->prepare($query);
        $rows=$sql->execute($this->escape);

        return $sql->fetchAll(PDO::FETCH_ASSOC);
    }

    public function count($query)
    {
        $sql = $this->pdo->prepare($query);
        $rows=$sql->execute($this->escape);

        return $sql->rowCount();
    }

All other databables implementation modify query so query itself will count records like select count(*)  from table/

**Comment by n1crack** [comment]
thanks for using the library.

I'm working on 2.0 version of the library. And just updated the count queries for Mysql and Sqlite dbs. (need to test for other libraries) https://github.com/n1crack/datatables/commit/6cd56bb83f6d731d61f6b518cf318d621939a9bf
It must be faster.  Can you try it with: 
````
composer require ozdemir/datatables:dev-2.0
```` 

if you have any suggestions please let me know.

**Comment by n1crack** [comment]
2.0 released. Please let me know if there is any further inconvenience.
