### ISSUE TITLE
why not data

### ISSUE THREAD

**Issue by 24775714** [n1crack/Datatables#4]
hello,you have done a good work,but when do your example,my get following:

{"draw":false,"recordsTotal":"269","recordsFiltered":"269","data":[]}

not data showing?

**Comment by n1crack** [comment]
Can you share your codes? I need more information

**Comment by Sancer** [comment]
If browser testing , data delivery empty array.
If there is a problem in the past fields in the SELECT empty array also delivers data.

**Comment by n1crack** [comment]
When you try it on your browser, it does not recognize limit values. 
You can try adding ajax.php?start=0&length=10  values to define it for now. 
I will add this as default on the next patch.
