### ISSUE TITLE
fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by steinhaug** [n1crack/datatables#42]
I installed by using composer, my .json looks like this:

    "require": {
        "ozdemir/datatables": "2.*",
        "symfony/http-foundation": "^4.2"
    },

My "/api/index.php" which should serve the data looks like this:

    <?php
    require_once '../../vendor/autoload.php';

    use Ozdemir\Datatables\Datatables;
    use Ozdemir\Datatables\DB\MySQL;

    $config = [ 'host'     => 'localhost',
                'port'     => '3306',
                'username' => 'db_user',
                'password' => 'db_pass',
                'database' => 'database' ];

    $dt = new Datatables( new MySQL($config) );
    $dt->query('SELECT id, domain, ip from domains LIMIT 20');
    echo $dt->generate();
    ?>

When I access this directly it looks like its working, however when accessed from webpage this is the URL being created:

    /api/index.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1544930408846

This gives me theese cryptic messages in return

    ( ! ) Fatal error: Uncaught TypeError: Return value of 
    Ozdemir\Datatables\Iterators\ColumnCollection::get() must be an instance of 
    Ozdemir\Datatables\Column, none returned in 
    D:\dev\vendor\ozdemir\datatables\src\Iterators\ColumnCollection.php on line 73
    --
    1 | 0.2043 | 416568 | {main}( ) | ...\index.php:0
    2 | 0.2135 | 1146768 | Ozdemir\Datatables\Datatables->generate( ) | ...\index.php:16
    3 | 0.2135 | 1146768 | Ozdemir\Datatables\QueryBuilder->setColumnAttributes( ) | ...\Datatables.php:176
    4 | 0.2136 | 1147648 | Ozdemir\Datatables\Iterators\ColumnCollection->get( ) | ...\QueryBuilder.php:96

What am I doing wrong here, I have used this HTML:

    <table border="0" class="display" id="example" width="100%">
        <thead>
        <tr>
            <th>ID</th>
            <th>Track Name</th>
            <th>Album</th>
            <th>MediaType</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>loading...</td>
        </tr>
        <tfoot>
        <tr>
            <th>ID</th>
            <th>Track Name</th>
            <th>Album</th>
            <th>MediaType</th>
        </tr>
        </tfoot>
        </tbody>
    </table>

And this javascript:

    <script>

        $(document).ready(function() {

            // Setup - add a text input to each footer cell
            $('#example tfoot th').each( function () {
                var title = $(this).text();
                    $(this).html( '<input type="text" class="input is-small" placeholder="Search '+title+'" />' );
            } );

            // DataTable
            var table = $('#example').DataTable( {
                "serverSide": true,
                "responsive": true,
                "ajax": "/api/index.php"
            } );

            // Apply the search
            table.columns().every(function () {
                // Apply the filter
                $("#example tfoot input").on( 'keyup change', function () {
                    table
                        .column( $(this).parent().index()+':visible' )
                        .search( this.value )
                        .draw();
                } );
            });

        } );

    </script>

**Comment by n1crack** [comment]
Hey, first ty for using the library.

The error occured because there are more columns defined in your html setup.
```
<table border="0" class="display" id="example" width="100%">
    <thead>
    <tr>
        <th>ID</th>
        <th>Domain</th>
        <th>IP</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>loading...</td>
    </tr>
    <tfoot>
    <tr>
        <th>ID</th>
        <th>Domain</th>
        <th>IP</th>
    </tr>
    </tfoot>
    </tbody>
</table>
```

I've updated the library anyway for that error.  If you run `composer update ` , there should'nt be any problem.

Please let me know,If it does'nt work.
