### ISSUE TITLE
Error CodeigniterAdapter on tag 2.0.0

### ISSUE THREAD

**Issue by zahidmuhammadzaki** [n1crack/datatables#43]
I use php 5.6 for my old project, and composer choose package v2.0.0.

I get the error on CodeigniterAdapter.

```
$query = "Select count(*) as rowcount from ($query)t";
$data = $this->CI->db->query($query, $query->escapes)->result_array();
```

I know its fixed on v2.0.1. But it require php 7.*.

I want to fix that. But i dont know how to commit to the older tag.

**Comment by n1crack** [comment]
You can install 1.7.1 version by:

`composer require ozdemir/datatables:1.7.1`
