### ISSUE TITLE
Datatable File Displays Cache Header

### ISSUE THREAD

**Issue by OssamaRafique** [n1crack/datatables#44]
**ajax.php**
```
<?php
    require_once('config/config.php');

    require_once 'vendor/autoload.php';

    use Ozdemir\Datatables\Datatables;
    use Ozdemir\Datatables\DB\MySQL;

    $dt = new Datatables( new MySQL([ 'host'     => DB_HOST,
                'port'     => DB_PORT,
                'username' => DB_USER,
                'password' => DB_PASS,
                'database' => DB_NAME ]));

 $dt->query('Select role_id, role_type from user_roles');

   echo $dt->generate()->toJson(); // same as 'echo $dt->generate()';
    ?>
```
**index.php**
```

    <!DOCTYPE html>
    <html>
    <head>
    	<title></title>
    	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css
">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css

">
    </head>
    <body>
    	<table border="0" class="display" id="example" width="100%">
    <thead>
    <tr>
        <th width="50%">role_id</th>
        <th width="50%">role_type</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>loading...</td>
    </tr>
    </tbody>
</table>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script type="text/javascript">
$(document).ready(function () {
  $('#example').dataTable({
      "serverSide": true,
      "responsive": true,
      "ajax": "ajax.php"
  });
});
    </script>

    </body>
    </html>

```
**Response in xampp**
![image](https://user-images.githubusercontent.com/32899991/51038972-436e5680-15d6-11e9-82af-fef640f8508e.png)

**Response in Ampps on php 7.1**

`Fatal error: Uncaught PDOException: could not find driver in C:\Program Files (x86)\Ampps\www\test\vendor\ozdemir\datatables\src\DB\MySQL.php:45 Stack trace: #0 C:\Program Files (x86)\Ampps\www\test\vendor\ozdemir\datatables\src\DB\MySQL.php(45): PDO->__construct('mysql:host=loca...', 'root', '') #1 C:\Program Files (x86)\Ampps\www\test\vendor\ozdemir\datatables\src\Datatables.php(59): Ozdemir\Datatables\DB\MySQL->connect() #2 C:\Program Files (x86)\Ampps\www\test\ajax.php(29): Ozdemir\Datatables\Datatables->__construct(Object(Ozdemir\Datatables\DB\MySQL)) #3 {main} thrown in C:\Program Files (x86)\Ampps\www\test\vendor\ozdemir\datatables\src\DB\MySQL.php on line 45`

**Comment by n1crack** [comment]
Seems something that related to :
https://www.w3.org/International/questions/qa-byte-order-mark.en#problems

You can try saving the files without BOM (remove bom)
https://www.w3.org/International/questions/qa-byte-order-mark.en#remove

**Comment by OssamaRafique** [comment]
I recreated the files on my namecheap shared hosting via cpanel and copy pasted my code.
I am getting different error this time

> 
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/crafctuz/ossamarafique.com/datatable/vendor/ozdemir/datatables/src/Datatables.php on line 68

Please review it here  : 
https://www.ossamarafique.com/datatable/index.php
https://www.ossamarafique.com/datatable/ajax.php

**Comment by OssamaRafique** [comment]
After changing php version to 7.3 error is changed
`Fatal error: Uncaught PDOException: could not find driver in /home/crafctuz/ossamarafique.com/datatable/vendor/ozdemir/datatables/src/DB/MySQL.php:45 Stack trace: #0 /home/crafctuz/ossamarafique.com/datatable/vendor/ozdemir/datatables/src/DB/MySQL.php(45): PDO->__construct('mysql:host=loca...', 'crafctuz_test', 'crafctuz_test') #1 /home/crafctuz/ossamarafique.com/datatable/vendor/ozdemir/datatables/src/Datatables.php(59): Ozdemir\Datatables\DB\MySQL->connect() #2 /home/crafctuz/ossamarafique.com/datatable/ajax.php(29): Ozdemir\Datatables\Datatables->__construct(Object(Ozdemir\Datatables\DB\MySQL)) #3 {main} thrown in /home/crafctuz/ossamarafique.com/datatable/vendor/ozdemir/datatables/src/DB/MySQL.php on line 45`

**Comment by OssamaRafique** [comment]
**Now after changing PHP version to 7.1 Errors are gone but the same problem again**

```
{"draw":0,"recordsTotal":2,"recordsFiltered":2,"data":[["1","admin"],["2","user"]]}HTTP/1.0 200 OK
Cache-Control: no-cache, private
Content-Type:  application/json
Date:          Fri, 11 Jan 2019 15:16:40 GMT

{"draw":0,"recordsTotal":2,"recordsFiltered":2,"data":[["1","admin"],["2","user"]]}
```

**Comment by n1crack** [comment]
You need to have a module called pdo_mysql. Can you look for it in phpinfo() ?

**Comment by OssamaRafique** [comment]
Now, PHP version is 7.3 and I enabled pdo_mysql. 
Problem is same, it is showing the headers.

**Comment by n1crack** [comment]
Couldn't reproduce the error. Sorry.

Can you try 
````php
echo json_encode( $dt->generate()->toArray() );
````

**Comment by OssamaRafique** [comment]
I tried this already it works but the original function doesn't that's why asking.
Anyway on xampp v3.2.2 it is not working it is showing this error 
Parse error: syntax error, unexpected ';', expecting ',' or ')' in C:\xampp_7.1\htdocs\sportsgear\ajax.php on line 33

**Comment by n1crack** [comment]
I think this is something related to webserver settings 
Can you check nginx setup or .htaccess file if you are using apache.

**Comment by OssamaRafique** [comment]
I already used above thing, But the default method was not working that's why I opened the issue.
My .htaccess code ::
```
#turn on url rewriting 
RewriteEngine on
#remove the need for .php extention 
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteCond %{REQUEST_FILENAME}\.php -f 
RewriteRule ^(.*)$ $1.php
ErrorDocument 404 /404-error.php
ErrorDocument 403 /assets/pages/403.php
```
But it has nothing to do with that header output.

**Comment by OssamaRafique** [comment]
This error is showing on my both local server and NameCheap shared hosting.

**Comment by n1crack** [comment]
removed dependency of symfony,  can you update the library and test it ?

**Comment by OssamaRafique** [comment]
Its working now, Thank you! 👍
