### ISSUE TITLE
PSAdapter escape is missing single quote

### ISSUE THREAD

**Issue by stefanovita** [n1crack/datatables#46]
Using the PSAdapter with Prestashop 1.7 the search query is broken since no single quotes are added to the where conditions. 
A quick workaround is to modify the escape method:
```php
/**
* @param $string
* @param Query $query
* @return string
*/
public function escape($string, Query $query)
{
     return "'" . pSQL($string) . "'";
 }
```

**Comment by n1crack** [comment]
Does the 1.7 version OK ? If so I'll get it done.

**Comment by stefanovita** [comment]
Thank you!
