### ISSUE TITLE
Newbie Issues...

### ISSUE THREAD

**Issue by tdaumit** [n1crack/Datatables#5]
Thank you for posting this git, your a life saver. I'm fairly new at using php, and am running into a few issues. 

I didn't use composer, instead just copied over the required documents. I also created the "composer.json" file and put it in the root folder.

My questions/issues:

1. What is "namespace Ozdemir\Datatables\DB"? I can't find these folders. 

2. In the ajax.php file it calls for:  
              use Ozdemir\Datatables\Datatables;
              use Ozdemir\Datatables\DB\MySQL;
What are these doing? If I am calling my own database, do these change?

Thanks!

**Comment by n1crack** [comment]
there are some explanations are here about namespacing and use statements. 
http://php.net/manual/en/language.namespaces.basics.php
http://stackoverflow.com/questions/10542012/php-namespaces-and-use 


If you want to make your own database connection. You should create a db connection class that implements DatabaseInterface class like : 
for mysql
https://github.com/n1crack/Datatables/blob/master/src/DB/MySQL.php
for sqlite
https://github.com/n1crack/Datatables/blob/master/src/DB/SQLite.php
