### ISSUE TITLE
Array access with invalid values return E_NOTICE since PHP 7.4 and may break queries

### ISSUE THREAD

**Issue by fdelapena** [n1crack/datatables#51]
I'm getting this with E_NOTICE enabled which breaks the query since PHP 7.4:

> **Notice**:  Trying to access array offset on value of type null in **vendor/ozdemir/datatables/src/QueryBuilder.php** on line **214**

And this one twice for each column:
> **Notice**:  Trying to access array offset on value of type null in **vendor/ozdemir/datatables/src/Column.php** on line **101**

Details on this [tweet](https://twitter.com/nikita_ppv/status/1148931277216800769).

**Comment by n1crack** [comment]
Yeah, I’ll look into it tonight.

**Comment by n1crack** [comment]
refactored the code. It seems working now. 

If you find any bugs, I would be appreciated if you tell me.

https://github.com/n1crack/datatables/commit/1427c04881d66222de99db812f9c6665483d8116

**Comment by fdelapena** [comment]
Updated from composer, it works flawless so far and the new code looks nice. Thank you for the fast update!
