### ISSUE TITLE
Codeigniter - Order by Columns not working, ozdemir/datatables:^2.2

### ISSUE THREAD

**Issue by ragshion** [n1crack/datatables#52]
I'm using ozdemirdatatables in codeigniter 3.1.6, try ordering by column but not working... 

`SELECT pelapor.nik, pelapor.nama_lengkap, kategori.kategori, laporan.id, laporan.isi_laporan, laporan.lokasi_kejadian, laporan.latlng, laporan.status, laporan.disposisi, opd.nama_opd, laporan.tgl_input FROM laporan join kategori on kategori.id=laporan.kategori join pelapor on pelapor.nik=laporan.nik left join opd on opd.id=laporan.disposisi order by laporan.status asc`

Thanks' :D

**Comment by n1crack** [comment]
I'll fix it but can you change the last part and try again pls ? 

order by laporan.status asc   => . order by status asc

**Comment by ragshion** [comment]
i've change to `order by status asc` . but it doesn't work... the column ordering is stil order by first column i select ( `pelapor.nik` )

**Comment by n1crack** [comment]
You can set default ordering in the javascript options by doing:

```
”order”: [[ 3, “desc” ]]
```

See details here: https://datatables.net/examples/basic_init/table_sorting.html 

If there is an error alert, can you share the console logs with me?

**Comment by ragshion** [comment]
oke thanks it's work when i'm ordering using datatables javascript... but, i think it's should be great if i can ordering by sql select..
here is my full code
`$datatables = new Datatables(new CodeigniterAdapter);
		$datatables->query('SELECT pelapor.nik, pelapor.nama_lengkap, kategori.kategori, laporan.id, laporan.isi_laporan, laporan.lokasi_kejadian, laporan.latlng, laporan.status, laporan.disposisi, opd.nama_opd, laporan.tgl_input FROM laporan join kategori on kategori.id=laporan.kategori join pelapor on pelapor.nik=laporan.nik left join opd on opd.id=laporan.disposisi order by laporan.status asc');
        
        $datatables->hide('id');
        $datatables->hide('latlng');
        $datatables->hide('tgl_input');
        $datatables->hide('disposisi');
        $datatables->edit('status', function($data){
        	if ($data['status'] == '0') {
                return '<span class="badge badge-default">Belum Diproses</span>';
            }else if ($data['status'] == '1') {
                return '<span class="badge badge-info">Terverifikasi</span>';
            }else if ($data['status'] == '2') {
                return '<span class="badge badge-warning">Ditindaklanjuti</span>';
            }else {
                return '<span class="badge badge-success">Selesai</span>';
            }
        });

        $datatables->add('action', function ($data) {
		    return '<button class="btn btn-secondary" onclick="detail_laporan(`'.$data['id'].'`)"><i class="fa fa-info"></i> Detail</button> <a class="btn btn-danger" href="javascript:;" onclick="hapus_laporan('.$data['id'].')" role="button"><i class="fa fa-trash"></i> Hapus</a>';
		    // <a class="btn btn-warning" href="javascript:;" onclick="ubah_laporan('.$data['id'].')" role="button"><i class="fa fa-edit"></i> Ubah</a> 
		});

        echo $datatables->generate();`

**Comment by n1crack** [comment]
if you are going to leave sorting to sql, still you should set the order option as an empty array:

```

  "order": []

```


Do you get any errors ?

**Comment by ragshion** [comment]
if i'm set `"order" : []` in datatables javascript instead off `"order" : [[5, "asc"]]`, order by columns not working and i don't get any error. It's still order by first column I select in sql

**Comment by durango25** [comment]
I have the same problem.
