### ISSUE TITLE
Encoding arabic character issue

### ISSUE THREAD

**Issue by sorryjack** [n1crack/datatables#53]
I got issue with arabic encoding. Its fine using native server side by datatable, but read as strange character when using your repo. please help.
ÙˆÙ‚Ø§Ù„Øª Ø²ÙŠÙ†Ø¨Ù : Ø£Ù†Ø§ .... ÙˆØ£Ù†Ø§ Ù‚ÙŽØ§Ø¯ÙÙ…ÙŽØ©ÙŒ Ù…Ù† Ù…ÙŽØ§Ù„ÙÙŠÙ’Ø²ÙÙŠÙŽØ§
![image](https://user-images.githubusercontent.com/6811578/73944829-d090f580-4925-11ea-99ec-f34552be96b2.png)

**Comment by n1crack** [comment]
hey,
try the solution below.    thanks for using the library, 

![Ekran Resmi 2020-02-06 22 22 26](https://user-images.githubusercontent.com/712404/73970987-2e760b00-492f-11ea-800e-b3ebfec2b1ae.png)

![Ekran Resmi 2020-02-06 22 17 29](https://user-images.githubusercontent.com/712404/73970615-82342480-492e-11ea-92c2-c1c871efbb6e.png)

**Comment by sorryjack** [comment]
This gave me error
![image](https://user-images.githubusercontent.com/6811578/74025371-608e7800-49d6-11ea-9097-59b614b6728f.png)
![image](https://user-images.githubusercontent.com/6811578/74025388-6d12d080-49d6-11ea-9cb0-8ef58007357a.png)

**Comment by sorryjack** [comment]
when I use "encode" it is not error, or just return the original data.

**Comment by sorryjack** [comment]
well, this solved by removing charset setting in the src > Mysql DB setup
![image](https://user-images.githubusercontent.com/6811578/74025950-adbf1980-49d7-11ea-850f-7ff23cc1b66b.png)
![image](https://user-images.githubusercontent.com/6811578/74025994-c4657080-49d7-11ea-934a-f793fb381683.png)

please tell me is this a permanent solution for me or could you provide better solution?

**Comment by n1crack** [comment]
It is, for now. 

I can add an option for charsets later.

**Comment by sorryjack** [comment]
Thanks.. 
And I want to ask about
- how to use dt features like modify column, putting in index number instead of id from db, etc?

**Comment by n1crack** [comment]
I havent used the dt features before.   you can try these:

````php
$dt->add('DT_RowID', function ($data){
    return 'rowid_'.$data['id'];
});

$dt->add('DT_RowClass', function ($data){
    return 'rowclass_'.$data['id'];
});

$dt->add('DT_RowData', function ($data){
    return 'rowdata_'.$data['id'];
});

$dt->add('DT_RowAttr', function ($data){
    return 'rowattr_'.$data['id'];
});
````
