### ISSUE TITLE
 Column name on return

### ISSUE THREAD

**Issue by wallysonn** [n1crack/datatables#56]
Is it possible to change the result where each column is numbered for the names? Example:
Currently the result is this
```
[
 ...
[ 
0: 'Mary',
1: 25
]
...
 ]
```

I would like to see it like this

```
[
 ...
[ 
'name': 'Mary',
'age': 25
]
...
 ]
```

**Comment by n1crack** [comment]
Yes it is possible 

https://datatables.ozdemir.be/object-data-source

**Comment by wallysonn** [comment]
> Yes it is possible
> 
> https://datatables.ozdemir.be/object-data-source


Incredible solution. Congratulations!
