### ISSUE TITLE
How to get working without composer

### ISSUE THREAD

**Issue by super-tomcat** [n1crack/datatables#58]
hi, i dont want to go down the route of using Composer and ive tried downloading the source and re-creating the folders and then tried the basic.php script..... however i keep getting:

Fatal error: Uncaught Error: Class 'Ozdemir\Datatables\Datatables' not found in C:\wamp64\www\basic.php on line 15
Error: Class 'Ozdemir\Datatables\Datatables' not found in C:\wamp64\www\basic.php on line 15

So what could i be doing wrong? Thanks

**Comment by n1crack** [comment]
you have to include the classes yourself since there is no composers autoloader class.

```php
<?php 
//correct these paths for your setup
include_once "Datatables/Datatables.php";
include_once "Datatables/DB/DatabaseInterface.php";
include_once "Datatables/DB/SQLite.php";

use Ozdemir\Datatables\Datatables;
use Ozdemir\Datatables\DB\SQLite;

// using SQLite as DB for the examples. Change here to fit your db.
$path = dirname(__DIR__).'/database/Chinook_Sqlite_AutoIncrementPKs.sqlite';
$dt = new Datatables(new SQLite($path));

$dt->query('Select TrackId, Name, UnitPrice from Track');

echo $dt->generate();

```

**Comment by super-tomcat** [comment]
ok, many thanks trying to help... i tried with the version (which is the latest) i have after making your changes above and i got this:

Fatal error: Class 'Ozdemir\Datatables\DB\DBAdapter' not found in C:\wamp64\www\Ozdemir\Datatables\DB\SQLite.php on line 12

And how do i get version 1.7? thanks

**Comment by n1crack** [comment]
i strongly advise you to use version 2+ with composer.
but still if you cant. you should find the DBAdapter (and for the other classes, there will be more errors like this.)

or   download the 1.7.1 version from https://github.com/n1crack/datatables/releases/tag/1.7.1

**Comment by super-tomcat** [comment]
Thanks for all your help, but my limitations lie with datatables itself, i already setup the normal datatable to read json file however i needed to get the state of checkboxes (on/off) including the data on each row, back to my php file... i tried with sessions and cookies and that worked fine, unfortunately cookies can only hold so much data.... which was not enough! I also looked at local storage instead of cookies but i struggled being able to only read the data in another PHP page using $get, $post etc as i needed to update the data as and when the checkboxes are turned off/on.... maybe i have to write my own table in PHP!
