### ISSUE TITLE
Query with subselect columns error

### ISSUE THREAD

**Issue by andrejflorjancic** [n1crack/datatables#6]
If query has subselect of any kind, function setcolumns return empty string. I found a solution:

private function setcolumns($query)
{
$query = preg_replace("/\(([^()]|(?R))*\)/i", "", $query);
.....
}

**Comment by n1crack** [comment]
Can you post your query string ?

**Comment by andrejflorjancic** [comment]
I can not post my queries, because you will not be able to test. Therefore, I have prepared two queries. Both return an error.

SELECT column_name,
       (SELECT group_concat(cp.GRANTEE)
          FROM COLUMN_PRIVILEGES cp
         WHERE     cp.TABLE_SCHEMA = COLUMNS.TABLE_SCHEMA
               AND cp.TABLE_NAME = COLUMNS.TABLE_NAME
               AND cp.COLUMN_NAME = COLUMNS.COLUMN_NAME)
          privs
  FROM COLUMNS
 WHERE table_schema = 'mysql' AND table_name = 'user';
 
SELECT column_name
  FROM COLUMNS
 WHERE table_schema = 'mysql' AND table_name = 'user'
   and (SELECT group_concat(cp.GRANTEE)
          FROM COLUMN_PRIVILEGES cp
         WHERE     cp.TABLE_SCHEMA = COLUMNS.TABLE_SCHEMA
               AND cp.TABLE_NAME = COLUMNS.TABLE_NAME
               AND cp.COLUMN_NAME = COLUMNS.COLUMN_NAME) is not null;

**Comment by andrejflorjancic** [comment]
I made a correction in regular expression.

**Comment by n1crack** [comment]
Well, your correction didn't work for me. 

Can you try (I haven't tested it yet) :


```
    function setcolumns($query)
     {
        $query = $this->explode("FROM", $query);
        preg_match_all("/SELECT([\s\S]*)/i", $query[0], $columns);
        $columns = $this->explode(",", $columns[1][0]);

        // gets alias of the table -> 'table.column as col' or 'table.column col' to 'col'
        $regex[] = "/([\s\S]*)\s+as\s+(.*)/i";
        $regex[] = "/[\s\S]+(\([^()]+\))?\s+(.+)/i";
		
        // wipe unwanted characters => '`" and space
        $regex[] = '/[\s"\'`]+/';
        // if there is no alias, return column name -> table.column to column
        $regex[] = "/([\w\-]*)\.([\w\-]*)/";
		
        return preg_replace($regex, "$2", $columns);
    }

```

**Comment by andrejflorjancic** [comment]
Also doesn't work.
For first query result is:
**array (size=2)
  0 => string 'column_name' (length=11)
  1 => string '' (length=0)**
for second:
**array (size=1)
  0 => string '' (length=0)**

**Comment by andrejflorjancic** [comment]
Here is example that works  for me:

 function setcolumns($query)
    {
        $query = preg_replace("/\(([^()]|(?R))*\)/i", "", $query);
        preg_match_all("/SELECT([\s\S]*?)((\s*)FROM(?![\s\S]*\)))([\s\S]*?)/i", $query, $columns);

        $columns = $this->explode(",", $columns[1][0]);

        // gets alias of the table -> 'table.column as col' or 'table.column col' to 'col'
        $regex[] = "/(.*)\s+as\s+(.*)/i";
        $regex[] = "/.+(\([^()]+\))?\s+(.+)/i";
        // wipe unwanted characters => '`" and space
        $regex[] = '/[\s"\'`]+/';
        // if there is no alias, return column name -> table.column to column
        $regex[] = "/([\w\-]*)\.([\w\-]*)/";

        return preg_replace($regex, "$2", $columns);
    }

**Comment by n1crack** [comment]
Interesting. You did replace whole function , didnt you? 
I will look into it when I get home.

**Comment by andrejflorjancic** [comment]
I only add this line **$query = preg_replace("/(([^()]|(?R)))/i", "", $query);** in old function.

**Comment by n1crack** [comment]
Hey,
your function gives me the error below.

> warning: preg_replace(): Compilation failed: recursive call could loop indefinitely at offset ...


instead I used this one and it seems ok. Can you try it ? My tests passes on this one.
```
$query = preg_replace("/\((?:[^()]+|(?R))*+\)/i", "", $query);
```

**Comment by andrejflorjancic** [comment]
Yes, this works in all my cases. Thx.
