### ISSUE TITLE
in laravel it doesn't work

### ISSUE THREAD

**Issue by kevinnba13** [n1crack/datatables#60]
**Return this**

```
{
  "draw": 0,
  "recordsTotal": 4,
  "recordsFiltered": 4,
  "data": [
    [
      "3",
      "test"
    ],
    [
      "4",
      "test2"
    ],
  ]
}
```

**Should be:**

```
{
  "draw": 0,
  "recordsTotal": 4,
  "recordsFiltered": 4,
  "data": [
    {
      "id":"3",
      "name":"test"
    },
    {
      "id": "4",
      "name":"test2"
    }
  ]
}
```

**This is the request**
```
{
	"draw": 1,
	"columns": [{
		"data": "contractor_name",
		"name": "",
		"searchable": true,
		"orderable": true,
		"search": {
			"value": "",
			"regex": false
		}
	}, {
		"data": "name",
		"name": "",
		"searchable": true,
		"orderable": true,
		"search": {
			"value": "",
			"regex": false
		}
	}, {
		"data": "cod",
		"name": "",
		"searchable": true,
		"orderable": true,
		"search": {
			"value": "",
			"regex": false
		}
	}, {
		"data": "contract_cod",
		"name": "",
		"searchable": true,
		"orderable": true,
		"search": {
			"value": "",
			"regex": false
		}
	}, {
		"data": "supervisor_name",
		"name": "",
		"searchable": true,
		"orderable": true,
		"search": {
			"value": "",
			"regex": false
		}
	}, {
		"data": "status",
		"name": "",
		"searchable": true,
		"orderable": true,
		"search": {
			"value": "",
			"regex": false
		}
	}],
	"order": [{
		"column": 0,
		"dir": "asc"
	}],
	"start": 0,
	"length": 1,
	"search": {
		"value": "",
		"regex": false
	}
}
```

> **In codeigniter if it works**

**Comment by n1crack** [comment]
try this setup.. https://datatables.ozdemir.be/object-data-source

You should define the columns if you want the keys..

```javascript
$(document).ready(function () {
    $('#example').dataTable({
        "serverSide": true,
        "responsive": true,
        "ajax": "ajax/object-data-source.php",
        "columns": [
            {"data": "TrackId"},
            {"data": "Name"},
            {"data": "UnitPrice"}
        ]
    });
});
```

**Comment by kevinnba13** [comment]
> try this setup.. https://datatables.ozdemir.be/object-data-source
> 
> You should define the columns if you want the keys..
> 
> ```js
> $(document).ready(function () {
>     $('#example').dataTable({
>         "serverSide": true,
>         "responsive": true,
>         "ajax": "ajax/object-data-source.php",
>         "columns": [
>             {"data": "TrackId"},
>             {"data": "Name"},
>             {"data": "UnitPrice"}
>         ]
>     });
> });
> ```

I am doing the same, but the request is json with angular, apparently you are not receiving the post

![image](https://user-images.githubusercontent.com/9647763/87571595-4ac56300-c698-11ea-9f8b-cc12f5ab0727.png)

**Comment by n1crack** [comment]
what is the post/get parameters value ?

The library checks the data property and acts accordingly.. if it is not a number then it returns the keys.

![image](https://user-images.githubusercontent.com/712404/87598849-fb188300-c6fb-11ea-9fcf-357865289ea8.png)

![image](https://user-images.githubusercontent.com/712404/87598958-079cdb80-c6fc-11ea-8cf4-890601b82a26.png)

**Comment by fgc0109** [comment]
> $keys = $this->builder->isDataObject() ? $this->columns->names() : array_keys($this->columns->names());
> $this->builder->isDataObject() 

  is false  ,

>  if (!$this->options->columns()) {
>             return false;
>  }

is false

then 
I add options

> return array_intersect($data, $rangeSet) !== $data;

still false 

false  false  false  false  false  false  false  false 
forever false
forever use 

> array_keys($this->columns->names());

so nerver output column name
