### ISSUE TITLE
Problem with "order by"

### ISSUE THREAD

**Issue by abbasgholia** [n1crack/datatables#61]
ORDERING is not performed due to query sequence. Please help improve this article or section by expanding it
regard mostafa

**Comment by LeonBeilis** [comment]
@n1crack Hey, I think the issue not solved yet, I having issue with this at the current moment on a project I working on.
btw is there any way to order by default column (creation_date for example) if no order by provided.

**Comment by n1crack** [comment]
Can you try by adding `"order": []` to your javascript code.

Default order in your sql should work then.

**Comment by LeonBeilis** [comment]
> Can you try by adding `"order": []` to your javascript code.
> 
> Default order in your sql should work then.

Thanks for quick response, it did solve the order.
@n1crack

**Comment by abbasgholia** [comment]
thanks 
I did the same
regard by abbasgholia
