### ISSUE TITLE
Return value of Ozdemir\Datatables\Column::value() must be of the type string, null returned

### ISSUE THREAD

**Issue by moudarir** [n1crack/datatables#64]
Hello,

This issue is fired when the value from database is `NULL`.

![1st screenshot](https://user-images.githubusercontent.com/12732173/94364750-8d0d1680-00c3-11eb-92e7-4629d058ae36.png)
then
![2nd screenshot](https://user-images.githubusercontent.com/12732173/94364791-d2c9df00-00c3-11eb-8dbe-6f67a15d7c41.png)

To resolve this issue, we must remove `: sting`code typing in `public function value($row): string` or adding `?` mark before `string` for  => php7.2 like this
![3rd screenshot](https://user-images.githubusercontent.com/12732173/94364862-5a175280-00c4-11eb-8f64-94f0f68b6017.png)

Hope that can help someone.
Cordially.

**Comment by n1crack** [comment]
Thank you for reporting.
It will be fixed in the next release.
https://github.com/n1crack/datatables/commit/27309db1536ec503a29080cc61e14e71d866456e
