### ISSUE TITLE
#request Please add Codeigniter 4 adapter

### ISSUE THREAD

**Issue by kusmantopratama** [n1crack/datatables#65]
Please add Codeigniter 4 Adapter Thanks.

**Comment by kusmantopratama** [comment]
Please add Codeigniter 4 Adapter Thanks.

**Comment by n1crack** [comment]
Ty for using the library, ci4 adapter is added.

You can see the example here https://gist.github.com/n1crack/ff6f728ad22ddac33a690007197b318b

have a good day.

**Comment by kusmantopratama** [comment]
> Ty for using the library, ci4 adapter is added.
> 
> You can see the example here https://gist.github.com/n1crack/ff6f728ad22ddac33a690007197b318b
> 
> have a good day.

Thank you very much sir
