### ISSUE TITLE
Default order

### ISSUE THREAD

**Issue by andrejflorjancic** [n1crack/datatables#7]
Can you change **orderby()** default part . Please check if query has order inside, than use this order as default, not first column.

if ( ! is_array($dtorders))
{
return >>query has order by<<?"":$orders . $this->columns[0] . " asc";  // default
}

I have solution, can I send you by mail?

**Comment by n1crack** [comment]
I think it is not necessary. 
You can add an option parameter to javascript to order any column you want.

https://datatables.net/reference/option/order  

example :

```
$('#example').dataTable( {
    "order": [[ 3, 'asc' ], [ 1, 'asc' ]]
} );
```

**Comment by n1crack** [comment]
Btw, that default part works only if there is no header info. Datatables is sending the header info to sort first column as default

**Comment by andrejflorjancic** [comment]
I know well datatables option, but I want to have initial order completely different. I can not make that kind of order with columns in datatable.

**Comment by n1crack** [comment]
https://gist.github.com/n1crack/7467a9a991369cb44b1e4d6af4933ac2 
I made some changes for you in this gist. let me know about the results. You must add **"order": []** to your javascript.

Still when the user sorts the table via clicking columns, it will be ignored.

**Comment by andrejflorjancic** [comment]
No it is not good. If I have in **order by** something like **"case when c.data_type = 'STRING' then 1 else 0 end, c.column_name"**, than I got error **Unknown column 'c.data_type' in 'order clause''**.

My solution:

.....
$query = preg_replace("/\((?:[^()]+|(?R))*+\)/i", "", $query);
preg_match_all("/SELECT([\s\S]*?)((\s*)FROM(?![\s\S]*\)))([\s\S]*?)/i", $query, $columns);
$this->hasOrderIn = count(preg_grep("/(order\s+by)\s+(.+)$/i", explode("\n", $query)));
$columns = $this->explode(",", $columns[1][0]);
.....

....
if ( ! is_array($dtorders))
{
return $this->hasOrderIn?"":$orders . $this->columns[0] . " asc"; // default
}
....

**Comment by n1crack** [comment]
Nice one. ty. This will be added in the next patch.

**Comment by andrejflorjancic** [comment]
Thx
