### ISSUE TITLE
Add support for Embedded DataTable from Editor

### ISSUE THREAD

**Issue by callumgarven** [n1crack/datatables#79]
Hi there,

I'd like to suggest support for embedded DataTables from DataTables Editor.

Examples: https://editor.datatables.net/examples/datatables/
Field Type: https://editor.datatables.net/reference/field/datatable

This adds an embedded datatable to a DataTables editor instance which allows it to be used as a select, if the parent table that the editor is associated with is using AJAX, it will also pull the options from AJAX. (see the 'Server Script' on this example for an example: https://editor.datatables.net/examples/datatables/select.html - the AJAX data from the example also shows this data at the bottom)

See the DataTables Editor PHP Library implementation here: https://editor.datatables.net/docs/1.6.0/php/class-DataTables.Editor.Options.html

Thanks.

**Comment by n1crack** [comment]
I want the library to be as easy to use as possible. I don't want to complicate it with the Editor plugin. Thanks for the advise.
