### ISSUE TITLE
A small wish

### ISSUE THREAD

**Issue by andrejflorjancic** [n1crack/datatables#8]
Can you change all private functions to protected. A have written "class MySqlDatatables extends Datatables" that optimizes count of result rows. In this class I override methods query and execute.

class MySqlDatatables extends Datatables {

    public function query($query)
    {
        $this->columns = $this->setcolumns($query);
        $columns = implode(", ", $this->columns);
        $query = rtrim($query, "; ");
        $this->sql = "Select SQL_CALC_FOUND_ROWS $columns from ($query)t";

        return $this;
    }

    protected function execute()
    {
        $this->recordstotal = $this->db->count($this->sql); // unfiltered data count is here.
        $where = $this->filter();

        $this->data = $this->db->query($this->sql . $where . $this->orderby() . $this->limit());
        $rowCounts = $this->db->query("SELECT FOUND_ROWS() as rowCount");  // filtered data count is here.
        $this->recordsfiltered = $rowCounts[0]['rowCount'];

        $this->query = $this->sql . $where . $this->orderby() . $this->limit();

        return $this;
    }
}

**Comment by n1crack** [comment]
done :)

**Comment by andrejflorjancic** [comment]
thx
